### PR TITLE
Business analyst

### PR DESCRIPTION
**Pull request by SalmanQu**
Complete list of courses from the Business Analyst Nanodegree.

### CODE REVIEW

**Comment by mikesprague** [comment]
Thanks for the updates to the Predictive Analytics for Business Nanodegree. 

There's a numbering issue causing a conflict and not allowing a clean merge with the changes you made. 

I'm going to add the Machine Learning Nanodegree shortly so I'll also add the updated courses to the Predictive Analytics for Business Nanodegree and close the pull request versus asking you to fix it.

**Comment by mikesprague** [comment]
I just realized that while the numbering issue does exist in your pull request, the conflict was most likely a result of you not using an up to date version of the project for your changes.

Your date last updated was August 16 and the current date last updated is October 5. Please update your fork of the project before making changes and submitting in the future. Thanks!

**Comment by SalmanQu** [comment]
Hey,

The conflict arose for two reasons:

1. I changed the order of courses on Business Analyst Nanodegree. A/B Testing was pushed one place down.

2. I changed the date on"Last Updated".

I have updated my fork. I will do my best to avoid merging conflicts in future.

Regards

**Comment by mikesprague** [comment]
I agree, those were part of the issue. Those shouldn't have created an un-mergeable conflict, though.

When I took a closer look, your fork was a commit behind. My current version, prior to today's updates, was from October 5 and yours was being updated from August 16 so it was missing commits.

That ended up being the main reason I couldn't do a clean merge. Anyhow, no worries and, thanks for contributing!

**Comment by SalmanQu** [comment]
I see. I didn't realize that my fork was out of sync.

Glad to help.

*Salman Quaiyum*
*Electrical Engineer, Energy Technologist, Data Analyst*
Connect With Me <https://about.me/salmanq>

**Pull request closed without merging**
